### ISSUE TITLE
我路由器没有ppp.sh

### ISSUE THREAD

**Issue by GaryH4** [xiaopc/Fyoung-Keygen#2]
RT
没有ppp.sh，怎么用此程序呢
（华硕AC1200GU，自带linux）

**Comment by xiaopc** [comment]
基于 OpenWRT 的固件是这个文件,你可以考虑刷个固件😀

-----
至于华硕固件, 它调用 `pppd` 是通过一个 C 程序实现的, 而不是像 OpenWRT 用的 shell 脚本
所以, 要么得重新编译固件, 要么得把这个项目改成 `pppd` 插件...

**Comment by xiaopc** [comment]
如果不嫌麻烦,可以先本地生成用户名以后拨号...

**Comment by GaryH4** [comment]
那我还是先用着破解路由器吧，（两个路由器，破解的只是用来拨号，华硕的当二级路由）
听营业厅的说今年不需要破解路由器，普通的pppoe就行
不过实测不行

and再等段时间大概就有移动宽带接入了，or电信又铺光纤扩容

**Comment by kongminhao** [comment]
@GaryH4 , 不是吧，校园宽带你还搞个华硕的路由器，真有钱。

**Comment by xiaopc** [comment]
AC1200GU 确实有点冷门
（闲鱼出掉买能刷 OpenWRT 的, 还便宜

编译 `pppd` 插件还要对应版本的工具链，实在太麻烦了

**Comment by GaryH4** [comment]
之前用的友华WR1200JS，觉得5G有时候搜不到，隔壁和我合租宽带的dalao也速度不太行（只有两根天线）
@kongminhao 我自己有NAS啊，得用千兆来传
ASUS这学期才买的，出什么出

**Comment by xiaopc** [comment]
有个 pppd 插件不知道能用不 https://github.com/syaoranwe/SCUNET/tree/master/code/%E5%A4%A9%E7%BF%BC%E9%A3%9Eyoung
