### ISSUE TITLE
关于主代码的一些修正

### ISSUE THREAD

**Issue by dihambo** [xiaopc/Fyoung-Keygen#3]
> 19-20秋季学期飞扬俱乐部招新的时候博主给了我这个代码，说是win10这里不太适合。让我自己去看看。当时c++很渣，渣到这些代码都看不懂。后来就搁置了。     
> 现在放假我又回来看了看，调试再加修改，终于发现了这个代码的一些问题，然后进行了一些些修改，并成功拨号。        
> 下面是我的一些修改意见。

> 我作的修改主要都是主程序中的修改。

### 1. [fyoung.c](https://github.com/xiaopc/Fyoung-Keygen/blob/master/fyoung.c)的47:
```c++ 
if (argc<3) return 0;
```
因为我的c++并不好,这里我运行的时候总是到这里就直接退出,不进行下面的代码.然后我将if的执行块加了花括号,就可以正常运行了.
```c++
if (argc<3) {return 0;}
```

### 2. [fyoung.c](https://github.com/xiaopc/Fyoung-Keygen/blob/master/fyoung.c)的48:
```c++
if (strstr(argv[1], "tyfy") == NULL){
        printf("%s", argv[1]);
    } 
```
这里我不知道为什么要判定账号里是否含"tyfy",可能老版本的账号里有?也不知道为什么不含"tyfy"的话就直接返回原账号.这里我把判定条件修改为不为空,以进行下面的步骤.
```c++
if (strstr(argv[1], "tyfy") != NULL){
        printf("%s", argv[1]);
    } 
```

### 3. [fyoung.c](https://github.com/xiaopc/Fyoung-Keygen/blob/master/fyoung.c)的54:
```c++
CalcRealID(argv[1]+4,argv[2],timestamp,userID);
```
这里我也不清楚为什么要把账号加4.因为我从系统事件查看器中找到的真实拨号账号是直接含原始账号的,所以我尝试着把这个"+4"去掉
```c++
CalcRealID(argv[1],argv[2],timestamp,userID);
```
最后发现这样修改后得出的账号是可以成功拨号的,所以我在此提出我的实践看法.

>希望博主给出意见,**毕竟我只是个新手菜鸟.**
> 现在由于没有可以进行烧录的开源路由器,目前还没有进行下一步对路由器的操作.但还在摸索,希望可以以后和博主进行交流学习.

**Comment by kongminhao** [comment]
第一条我不知道为啥，maybe你使用方法有问题？
第二, 这个tyfy是为了区分在学校拨号还是在家拨号。
第三，电信已改邪归正，允许直接使用pppoe拨号，故, 此项目已废弃。

**Comment by dihambo** [comment]
江安那里可以直接拨了，望江这里依然不可（这里是北园一舍）。不过还是感谢博主。
 
 
 
 
 
 
 

  -- 
 
 
 发自新浪邮箱客户端 
 
 
  
  在 1月15日 09:39，kongminhao <notifications@github.com> 写道： 
  第一条我不知道为啥，maybe你使用方法有问题？
 第二, 这个tyfy是为了区分在学校拨号还是在家拨号。
 第三，电信已改邪归正，允许直接使用pppoe拨号，故, 此项目已废弃。

**Comment by xiaopc** [comment]
这是当时逆完以后顺手写的，很多地方没写太完善，只是提供一个思路。

就代码而言，窝来逐条解释一下。
1. 窝不知道你用的是什么编译器及平台，这个程序是需要有两个额外参数来运行的（argc 表示命令行参数个数，在 Windows 及 Linux 上默认第一个参数是程序路径）。

2. 和 3 是同一个问题，在 [README](../blob/master/README.md) 里面写的很清楚，为了区别正常拨号和奠信的拨号方式（比如以后拿回家用或者校园网多拨），这个程序要求在原来的用户名前面加 `tyfy` 字母来表示使用奠信算号方法，否则返回正常的用户名，`argv[1]+4` 就是去掉多加的这四个字母。

路由器怎么操作，在 README 里面给了有位同学的教程可以参考。

另外`win10这里不太适合`是什么意思呀？

-----

@kongminhao 你，打，字，带，逗，号

**Comment by dihambo** [comment]
我也不清楚，当初群里给我这个代码的时候说只能在mac使用，win10说是可能有啥小毛病。具体什么意思我也不太清楚。很感谢。

**Comment by xiaopc** [comment]
这个是从 Mac 版的拨号器逆出来的，不是只能在 Mac 用（谁说的，lyx 吗

**Comment by dihambo** [comment]
哦哦，hhh应该是我当时理解错了吧，我当时在飞扬迎新群里知道的消息。头像和你GitHub的头像一样hh
